apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app-mysql
  namespace: todo-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: todo-app
        tier: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: change-me
        image: mysql:8
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: todo-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app-mysql
  namespace: todo-app
spec:
  ports:
  - port: 3306
  selector:
    app: todo-app
    tier: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todo-app
        tier: frontend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.34
        command: ['sh', '-c', '
          echo "Waiting for MySQL database to be ready...";
          while ! nc -z todo-app-mysql 3306; do
            echo "MySQL is not ready yet - sleeping for 2 seconds...";
            sleep 2;
          done;
          echo "MySQL database is ready - starting Todo App";
        ']
      containers:
      - env:
        - name: PORT
          value: '4040'
        - name: DB_HOST
          value: todo-app-mysql
        - name: DB_PASS
          value: change-me
        - name: DB_USER
          value: root
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: 0x113/todo-app:latest
        imagePullPolicy: Always
        name: todo-app
        resources:
          limits:
              cpu: 0.02
              memory: 64Mi
          requests:
              cpu: 10m
              memory: 32Mi
        ports:
        - containerPort: 4040
          name: todo-app-port
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: logs-volume
          mountPath: /logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app
  namespace: todo-app
spec:
  ports:
  - port: 80
    targetPort: todo-app-port
  selector:
    app: todo-app
    tier: frontend
  type: NodePort
